### ISSUE TITLE
Plugin not working for Flutter 

### ISSUE THREAD

**Issue by AjFaboom** [deep-rooted-co/juspay_flutter#13]
Hello guys I want to integrate your Juspay plugin in my flutter app but it's not working.
Below is my pubspec.yaml dependency section:

dependencies:
  flutter:
    sdk: flutter
  juspay_flutter:
    git:
      url: https://github.com/deep-rooted-co/juspay_flutter.git
      ref: 4ebb4b062a130d6612aad9c627bbc611d9b4c82f     .....I added SHA1 commit key as suggested in your Doc
      
I am getting error after running app:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:downloadHyperSdkAssets'.
> java.io.IOException: Server returned HTTP response code: 403 for URL: https://assets.juspay.in/hyper/assetConfig/android/{clientId}/AssetConfig.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1 

Please help me with this issue as soon as possible or you guys publish this plugin on pub.dev for everyone to use

**Comment by sachinsudheendra** [comment]
```
java.io.IOException: Server returned HTTP response code: 403 for URL: 
https://assets.juspay.in/hyper/assetConfig/android/{clientId}/AssetConfig.txt
```

You need to replace `clientId` by following the steps in README. `clientId` can be obtained by signing up with juspay.

**Comment by ChouhanAkshay** [comment]
@AjFaboom  did you got the solution for this?
